Remove keyring from gnome-compat-startup key
mate-desktop/mate-session-manager pull request #200
Opened 2019-03-22 09:34 UTC by milouse

Mate Desktop support /etc/xdg/autostart elements and gnome-keyring-daemon (GKD) add entries, which mention explicitely Mate desktop there. Thus this entry is redundant. On the other hand, this entry is responsible for a "start-all-subcomponent" of GKD, which block fine selection of components to load at startup.

I think this compat element is not needed any more.

Fix: https://github.com/mate-desktop/mate-session-manager/issues/182

2019-03-22 12:16 UTC, raveit65 commented
Hmm, with this commit my ssh key isn't unlock anymore after session start.
```
[rave@mother caja-actions]$ git pull
Enter passphrase for key '/home/rave/.ssh/id_rsa': 
```
All three gnome-keyring in autostart are there and enabled.
```
[root@mother rave]# ls -l /etc/xdg/autostart/ | grep gnome-keyring
-rw-r--r--  1 root root  8355  2. Mär 19:15 gnome-keyring-pkcs11.desktop
-rw-r--r--  1 root root  7976  2. Mär 19:15 gnome-keyring-secrets.desktop
-rw-r--r--  1 root root  6538  2. Mär 19:15 gnome-keyring-ssh.desktop
```
```
[rave@mother caja-actions]$ gsettings get org.mate.session gnome-compat-startup
['smproxy']
```
Looks like this is needed.

2019-03-22 13:06 UTC, milouse commented
Hum… very weird… can you check if you see gnome-keyring-ssh.desktop in the « startup applications » gui ? If not, it may be disabled by something else. Do you have such an entry: `~/.config/autostart/gnome-keyring-ssh.desktop` ?

If not, it's surely a bug in gnome-keyring-daemon.

2019-03-22 13:23 UTC, milouse commented
Oh, no, forget about my previous message. Your behaviour is normal.

In fact, Mate Desktop will spawn `gnome-keyring-daemon --login --daemonize` when `keyring` is present in `gnome-compat-startup`. The `--login` switch implies the `--unlock` option by using the PAM password to unlocking compoment.

Without it, the later `gnome-keyring-daemon --start` will just enable component, without unlocking them.

Thus my PR is wrong. The problem seems not to be in mate itself, but because the `--login` switch somehow enable **all** components, instead of waiting for the corresponding `--start` call, as explained in the man page.

We should may be investigate on the GKD part for now.

2019-03-22 13:32 UTC, milouse commented
Mmmmh I just found something unclear to me. [This line](https://github.com/mate-desktop/mate-session-manager/blob/8f35c049172ab4bb1f73069e6a98f29ab45c4c0b/mate-session/msm-gnome.c#L99) seems to indicate that mate-desktop spawn `gnome-keyring-daemon --start` instead of `gnome-keyring-daemon --login --daemonize`.

I'm not a C export, nor a Mate guru :( @raveit65, if you have time, can you check if it works for you when you:

1. Keep the `gnome-compat-startup` value as `['keyring', 'smproxy']`
2. Replace the above line 99 by:
```C
argv[0] = GNOME_KEYRING_DAEMON;
argv[1] = "--login";
argv[2] = "--daemonize";
argv[3] = NULL;
```

Thank you very much!

2019-03-22 16:58 UTC, raveit65 commented
> can you check if you see gnome-keyring-ssh.desktop in the « startup applications » gui ?

Yes, they are.

> Do you have such an entry: ~/.config/autostart/gnome-keyring-ssh.desktop ?

No
```
[rave@mother ~]$ ls -l .config/autostart/ | grep keyring
[rave@mother ~]$ 
```
With you last suggestion
```
--- a/mate-session/msm-gnome.c
+++ b/mate-session/msm-gnome.c
@@ -82,7 +82,7 @@ gnome_keyring_daemon_startup (void)
   gint         status;
   glong        pid;
   gchar       *end;
-  gchar       *argv[3];
+  gchar       *argv[4];
   gchar       *p;
   gchar       *name;
   const gchar *value;
@@ -96,8 +96,9 @@ gnome_keyring_daemon_startup (void)
 
   error = NULL;
   argv[0] = GNOME_KEYRING_DAEMON;
-  argv[1] = "--start";
-  argv[2] = NULL;
+  argv[1] = "--login";
+  argv[2] = "--daemonize";
+  argv[3] = NULL;
   g_spawn_sync (NULL, argv, NULL,
                 G_SPAWN_SEARCH_PATH | G_SPAWN_LEAVE_DESCRIPTORS_OPEN,
                 child_setup, NULL,
```
and
```
rave@mother ~]$ gsettings get org.mate.session gnome-compat-startup
['keyring', 'smproxy']
```
my login keyring won't be unlocked and after 10-15 sec a Warning pops up.
![Screenshot at 2019-03-22 16-23-04](https://user-images.githubusercontent.com/961604/54839404-17a0d880-4ccb-11e9-86cc-5c70b82f0e6b.png)
After i unlocked my keyring my ssh-key isn't unlock again.
```
[rave@mother caja-actions]$ git pull
Enter passphrase for key '/home/rave/.ssh/id_rsa': 
```
So it is much worse than before.

During testing my system crashes and i couldn't start firefox for some reasons.
Sorry , at the moment i am not amused.
Please test more for yourself, i am happy to test again a 100% tested PR.

2019-03-23 18:31 UTC, milouse commented
@raveit65 sorry for bothering you. In fact I'm not a mate developer and have no idea how to build and test part of mate desktop by myself. As you say in your first message that you were able to do so, I thought you were a Mate developer ready to help us.

I can try to test this by myself if you know where I can found some beginner information on how to build and test part of the desktop.

Thank you for your help and understanding.

2019-10-29 05:56 UTC, auvipy approved these changes

2026-05-28 21:18 UTC, vkareh requested changes
This causes regressions. I think a possible alternative is for msm to parse the XDG autostart files to determine what should be started, and then spawn keyring with the `--start --components=[pkcs11,secrets,ssh]` flags based on those desktop files.

2026-06-01 20:01 UTC, milouse commented
This is a very old work of mine, and it’s a long time I do not use mate anymore. I prefer close this MR now and let anyone more involved work on it again if it’s still an issue (I assume it is not, given nobody never really look at this for all this time xD)

2026-06-01 20:01 UTC, closed without merging